### ISSUE TITLE
Can't get godef

### ISSUE THREAD

**Issue by lukasmalkmus** [abourget/getting-started-with-golang#1]
OS: Windows 10

First time go user here. Found these instructions linked on the wiki at the official go repo.

The second step isnt working for me `go get -u github.com/abourget/godef/...`

> C:\Users\lukas> go get -u github.com/abourget/godef/...
> !# github.com/abourget/godef/go/sym
> C:\GoPath\src\github.com\abourget\godef\go\sym\sym.go:63: not enough arguments in call to ctxt.importer
> C:\GoPath\src\github.com\abourget\godef\go\sym\sym.go:67: cannot use func literal (type func(string) *"github.com/rogpeppe/godef/go/ast".Package) as type types.Importer in return argument
> C:\GoPath\src\github.com\abourget\godef\go\sym\sym.go:91: not enough arguments in call to "github.com/rogpeppe/godef/go/parser".ParseFiles
> C:\GoPath\src\github.com\abourget\godef\go\sym\sym.go:218: not enough arguments in call to types.ExprType
> !# github.com/abourget/godef/go/types
> C:\GoPath\src\github.com\abourget\godef\go\types\types.go:84: not enough arguments in call to "github.com/rogpeppe/godef/go/parser".ParseDir
> !# github.com/abourget/godef
> C:\GoPath\src\github.com\abourget\godef\godef.go:116: not enough arguments in call to "github.com/rogpeppe/godef/go/parser".ParseFile
> C:\GoPath\src\github.com\abourget\godef\godef.go:149: not enough arguments in call to types.ExprType
> C:\GoPath\src\github.com\abourget\godef\godef.go:158: not enough arguments in call to types.ExprType
> C:\GoPath\src\github.com\abourget\godef\godef.go:256: too many arguments in call to typ.Iter
> C:\GoPath\src\github.com\abourget\godef\godef.go:267: not enough arguments in call to types.ExprType
> C:\GoPath\src\github.com\abourget\godef\godef.go:288: too many arguments in call to typ.Underlying
> C:\GoPath\src\github.com\abourget\godef\godef.go:295: not enough arguments in call to "github.com/rogpeppe/godef/go/parser".ParseExpr
> C:\GoPath\src\github.com\abourget\godef\godef.go:347: not enough arguments in call to "github.com/rogpeppe/godef/go/parser".ParseFile
> C:\GoPath\src\github.com\abourget\godef\godef.go:362: not enough arguments in call to "github.com/rogpeppe/godef/go/parser".ParseFile
> C:\Users\lukas>

Ignore the _!_ before _#_. They were made to prevent markdown doing its job :)

**Comment by abourget** [comment]
woah! we should use the upstream now.. they fixed the issues for which I forked it.. I'll update it right away.

**Comment by abourget** [comment]
Oh was already fixed.  Closing this :)
